# Generated by Django 3.1 on 2020-08-06 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_grs', '0002_auto_20200806_1923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='id',
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
