# Generated by Django 3.1 on 2020-08-22 01:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('my_grs', '0005_auto_20200813_1831'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('user_id', 'movie_id')},
        ),
    ]
