# Generated by Django 3.1 on 2020-08-24 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_grs', '0007_movie_counter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['-counter', 'movie_id']},
        ),
    ]
