# Generated by Django 3.1 on 2020-08-26 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_grs', '0008_auto_20200824_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='tags',
            field=models.CharField(blank=True, default='None', max_length=1000),
        ),
    ]
