# Generated by Django 3.1 on 2020-08-26 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_grs', '0010_auto_20200826_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genres',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=300),
        ),
    ]
